### ISSUE TITLE
Binary delta updates

### ISSUE THREAD

**Issue by probonopd** [megahertz/electron-simple-updater#1]
Check [AppImageUpdate](https://github.com/probonopd/AppImageKit/tree/master/AppImageUpdate.AppDir), it uses [zsync-curl](https://github.com/probonopd/zsync-curl) for binary delta updates. Which means that going from nightly to nightly, you only download the few MB that have actually changed. Haven't checked how well it performs on Electron apps specifically, but I'd assume serious time and bandwidth savings.

**Comment by megahertz** [comment]
Thank you for this information. I've read about this, but I don't know how to integrate this feature quickly. Maybe I'll try to use AppImageUpdate later when I'll have more free time.

**Comment by megahertz** [comment]
Sorry, but it seems that it's not too easy implementing this feature for my purposes.

**Comment by probonopd** [comment]
It's as easy as running `appimagetool -u ...` on your AppDir. 1-2 lines of code maximum. Why do you think it's "not too easy"? What are you struggling with?
