### ISSUE TITLE
Downloads the same update multiple times

### ISSUE THREAD

**Issue by dhruvr** [megahertz/electron-simple-updater#11]
Consider scenaro. I have updates.json as
```json
{
    "linux-x64-prod": {
        "readme": "Second release",
        "update": "...",
        "install": "...",
        "version": "1.0.0"
    }
}
```
and then I host or publish this on a server. When my app runs it says 
```
{"level":"info","message":"Update for linux-x64-prod-v1.0.0 is not available","timestamp":"2017-01-31T15:03:57.501Z"}

```

that is perfectly valid. But now i make some changes and now I change the verrion to 2.0 as
```
{
    "linux-x64-prod": {
        "readme": "Second release",
        "update": "...",
        "install": "...",
        "version": "2.0.0"
    }
}
```
 and now I publish this `updates.json.` and push latest build. When I start my app. It says

```
{"level":"info","message":"Found version 2.0.0 at .....}
```
that is valid and then we get message

```
{"level":"info","message":"New version 2.0.0 has been downloaded","timestamp":"2017-01-31T15:13:05.173Z"}

```
but now I close my app and start the app. It shows new changes, but in logs we see
```
{"level":"info","message":"Found version 2.0.0 at ...}
```

It happens every time when I start app. I am expecting that it should not download version2.0 again as its already there. 

I am thinking of storing the version returned from response in a file and check , either to download it  or not.

**Comment by megahertz** [comment]
Did you rebuild your application or just change the version number in json? If not it's a normal behavior because updated build contains a version number.

**Comment by dhruvr** [comment]
@megahertz  Yes I changed version number in json

**Comment by megahertz** [comment]
You should rebuild your app with a new version number.

**Comment by dhruvr** [comment]
okay my mistake I got it both version in updates.json and package.json are mapped
