### ISSUE TITLE
How can we do partial updates?

### ISSUE THREAD

**Issue by shahidmau** [megahertz/electron-simple-updater#12]
I can see that this url contains file size of 39 mb. 
https://github.com/megahertz/electron-simple-updater/releases/download/darwin-x64-prod-v0.0.2/Simple.Updater.Example-0.0.2-mac.zip

Is there any way to update only html/css/js files which are actually used by the app?

Thanks for awesome library.

**Comment by megahertz** [comment]
Sorry, but I'm not going to support partially update. I think it's better to have a separated library/service for it (something like CodePush)
