### ISSUE TITLE
Private GitHub Repo

### ISSUE THREAD

**Issue by drew-russell** [megahertz/electron-simple-updater#14]
Can you confirm whether or this package will work with a private GitHub repo? If so, could you provide any additional detail on the setup steps required? 

I've been able to get auto-update working correctly on a public facing account but when I switch it over to a private repo it errors out.

The only reference to private accounts I can find is:

- adding the GitHub token to publisher.json 
- `"private": true,` in the root package.json example (not sure if this related or not)

**Comment by megahertz** [comment]
As I know it's not possible to share a link to private repo release without providing access to this repo. So I think it's not possible. The best solution is to create a public repo only for releases.
