### ISSUE TITLE
Version is not loaded from package.json

### ISSUE THREAD

**Issue by do-web** [megahertz/electron-simple-updater#17]
I have tried to use simple-updater with https://github.com/SimulatedGREG/electron-vue this boilerplate but the package.json is not loaded so the version and updater url is always empty.

In the index.js i tried this:

`import { app, BrowserWindow } from 'electron'
const updater = require('electron-simple-updater');

updater.init({
    checkUpdateOnStart: false,
    autoDownload: false
});

console.log(updater);`

but version is empty, why is the version and the update url not loaded from the package.json?

**Comment by megahertz** [comment]
I'll try to run it a bit later.

**Comment by do-web** [comment]
It seems that its up to webpack that this does not work, only the build version is working.

**Comment by megahertz** [comment]
I think so too. I'm going to create a test project in the beginning of the next week and try to fix that.

**Comment by megahertz** [comment]
The boilerplate works correctly for me. If you have problems with loading package.json you can import package.json and pass version and url options to updater.init method

**Comment by tance77** [comment]
I have the same issue. 
```
app.getName() //is returning 'Electron'
```

Also this is getting dumped to the console. "electron-simple-updater is not initialized". I tried initializing without the package.json by passing it the updates.josn url straight to the constructor.  I get the same message dumped to the console.

**Comment by tance77** [comment]
const updater = require("electron-simple-updater");

updater.init({
    url:"https://raw.githubusercontent.com/somefiller/text/to/repo/updates.json",
    checkUpdateOnStart: false,
    autoDownload:       false
});
