### ISSUE TITLE
Auto Update problems on Windows & Mac 

### ISSUE THREAD

**Issue by do-web** [megahertz/electron-simple-updater#18]
On Mac the update is starting and the downloading callback is triggered, but then nothing happens, the file is not downloaded and "update-downloaded" never called. It is here required to sign the app for mac that this works?

On Windows the update works.

**Comment by cinder92** [comment]
hey @do-web  did you figured out how to solve it? i have same issue!

**Comment by giacgbj** [comment]
@cinder92 https://github.com/megahertz/electron-simple-updater#usage, point 2.

**Comment by cinder92** [comment]
@giacgbj  yes thanks, my app is already signed, but update is not working...
