### ISSUE TITLE
ESU not finding "metadata for update. Run checkForUpdates first."

### ISSUE THREAD

**Issue by tjoye20** [megahertz/electron-simple-updater#19]
Hi,

Thank you for taking the time to build this module. However, I'm struggling to get this module working on my Mac machine, for my mac build, that I created with Electron packager and Electron Installer, but I keep getting this message: 

`There is no metadata for update. Run checkForUpdates first.
Update for darwin-x64-prod-v2.0.0 is not available
Update for darwin-x64-prod-v2.0.0 is not available`

Below is the link to see my updates.json, and the zip file, as well as the dmg installer for Mac:
[Update Repo with all the updates.json, packages, etc.](https://github.com/tjoye20/vthreat-updates/releases)

In my main.js, I have this code:
`const updater = require('electron-simple-updater');
 updater.init("https://github.com/tjoye20/vthreat-updates/releases/download/v2.0.0/updates.json")
 updater.checkForUpdates();
 updater.downloadUpdate();
`

Can you help me determine why it's not finding the metadata and downloading the update. The currently packaged version of the app is version 1.0.0, and the updates.json now is version 2.0.0

Your help would be greatly appreciated. 

-Tj

**Comment by megahertz** [comment]
Hi Tj. You don't need to call checkForUpdates and downloadUpdate, just keep updater.init("https://github.com/tjoye20/vthreat-updates/releases/download/v2.0.0/updates.json").

**Comment by tjoye20** [comment]
Hi! I got it working, kind of, but now I"m getting this error: Could not get code signature for running application,

even tho my package (.app folder) is signed. Or, should I be signing the .dmg image instead?

**Comment by tjoye20** [comment]
Here's the code signing verification:

`> vthreat@1.0.0 verify:osx-signature /Users/toluoyeniyi/Electron/vthreat-desktop
> spctl -a -vvvv dist/osx/'vThreat Bot-darwin-x64'/'vThreat Bot.app'/

dist/osx/vThreat Bot-darwin-x64/vThreat Bot.app/: accepted
source=Developer ID
origin=Developer ID Application:....`

**Comment by megahertz** [comment]
Both old (current) and new releases should be signed with the same certificate.
I don't use electron-packager so I can't help you with it. But with electron-builder I had no problems with signing.

**Comment by tjoye20** [comment]
OK. Well, it says it's downloading, `Downloading updates from https://github.com/tjoye20/vthreat-updates/releases/download/v2.0.0/vThreat.Bot.dmg`, but I've been waiting over 30 minutes and have even restarted the app, but it's still the same version number when I check what the package.json.version says. 

How do I know/check the update status, or know when it's down updating?

**Comment by megahertz** [comment]
It should download json file, not dmg. Check your links. Or use electron-simple-publisher instead.

**Comment by tjoye20** [comment]
Yes, that's what I was trying at first, and nothing was happening. 

I set it up like the links in the example, `Downloading updates from https://github.com/tjoye20/vthreat-updates/releases/download/v2.0.0/release.json`, and still, nothing happens. 

That release.json file contains this url: `https://github.com/tjoye20/vthreat-updates/releases/download/v2.0.0/vThreat.Bot.dmg.zip`, a .zip file of the image just like in the example.

**Comment by megahertz** [comment]
The format of this file is wrong, it should contain *.app folder, not dmg. Listen to the error event of updater.

**Comment by tjoye20** [comment]
Well, still struggling with this. I really appreciate your patience and your help tho. Thank you.

**Comment by megahertz** [comment]
I recommend you to use electron-simple-publisher together with electron-builder, it will make all necessary resource and links for you.

**Comment by megahertz** [comment]
@tjoye20 How's your progress?

**Comment by tjoye20** [comment]
I used Electron builder with electron-simple-publisher, and ran into the same issues. Getting this error: `Found version 2.0.0 at https://github.com/tjoye20/vthreat-updates/releases/download/v2.0.0/latest-mac.json
{ Error: Could not get code signature for running application
    at SimpleUpdater.onFoundUpdate (/Users/toluoyeniyi/Electron/vthreat-desktop/node_modules/electron-simple-updater/index.js:304:17)
    at getUpdatesMeta.then (/Users/toluoyeniyi/Electron/vthreat-desktop/node_modules/electron-simple-updater/index.js:159:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  preventDefault: [Function: preventDefault],
  sender:
   AutoUpdater {
     _events: { 'update-downloaded': [Function], error: [Function] },
     _eventsCount: 2 } }
Downloading updates from https://github.com/tjoye20/vthreat-updates/releases/download/v2.0.0/latest-mac.json
2017-03-22 09:29:58.871 Electron Helper[53931:14094011] Couldn't set selectedTextBackgroundColor from default ()`

**Comment by tjoye20** [comment]
If you're interested, would you be open to doing a quick 30 min MAX screenshare to help me troubleshoot this?

**Comment by megahertz** [comment]
It seems that you have created latest-mac.json by yourself, not using electron-simple-publisher. It contains a wrong link to zip.

I'll be available tomorrow. skype megahertz66

**Comment by tjoye20** [comment]
Yeah, I changed it while troubleshooting because it wasn't working before. It didn't actually publish anything to the link it created. 

What time, your time, are you available tomorrow?

**Comment by megahertz** [comment]
Between 9am and 15pm gmt+5

**Comment by tjoye20** [comment]
Fixed! Thank you for taking the time to help me through this. Great work on this module.
