### ISSUE TITLE
Differences between Electron-Simple-Updater and autoUpdater

### ISSUE THREAD

**Issue by MrBlenny** [megahertz/electron-simple-updater#2]
Could you outline the differences between this and [autoUpdater](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md)?

What are the benefits to each?
This would be very useful in the readme.md

Thanks 👍

**Comment by megahertz** [comment]
Hi David. Thanks for the suggestion. I'm going to update documentation in a few days and will add this information. 

The short answer: it uses autoUpdater inside, it has Linux support, it handles Squirrel.Windows commands, it does not require a dedicated server and it's just easier to setup.
