### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by godza** [megahertz/electron-simple-updater#20]
Hello,

Is there any way we can get event which lets us know what % of # of bytes is downloaded? If not, i think it would be worthy addition to this library.

Thanks

**Comment by megahertz** [comment]
Sorry, it's not possible because updates are downloaded outside this library (by Squirrel), except for linux.

**Comment by debelop13** [comment]
Here they want the same:
 
https://github.com/Squirrel/Squirrel.Mac/issues/200

Can be possible now?

**Comment by megahertz** [comment]
It seems that electron-updater uses a proxy to original update server. It's interesting, but requires a lot of work, so I'm not going to implement this feature in near future. But you're welcome to send a PR.
