### ISSUE TITLE
 It seems that the app is not in AppImage fromat (while it is)

### ISSUE THREAD

**Issue by nukeop** [megahertz/electron-simple-updater#21]
I'm using this package to a great effect in my music player.

One of the users reported an issue where he's unable to update the program automatically if he uses AppImage: https://github.com/nukeop/nuclear/issues/36

Any ideas what could cause this message?

Cheers

**Comment by megahertz** [comment]
I"ll check what's wrong tomorrow

**Comment by megahertz** [comment]
The webpack DefinePlugin overrides environment variables - that's why ESU doesn't work. Linux update module depends on process.env.APPIMAGE variable.

**Comment by NateMoeller** [comment]
I'm trying to do the same thing. Is there a solution to this? Or is it not possible to use DefinePlugin and ESU together? I've found that hard coding the path to process.env.APPIMAGE in DefinePlugin will get it to work, however I do not know how to generate that path within webpack.

**Comment by megahertz** [comment]
@NateMoeller try to use
```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production')
})
```

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.

**Comment by arvindrajan92** [comment]
Hi @megahertz,

I am getting the same message: "It seems that the app is not in AppImage format".

Could you provide a procedure to fix this? I am new to coding in this environment and therefore your help is greatly appreciated. Thank you.

Cheers.

**Comment by megahertz** [comment]
Hi @arvindrajan92. Could you provide more information? (configs, build procedure and so on)

**Comment by arvindrajan92** [comment]
Hi @megahertz,

Thank you for coming back. I am using electron-builder with build:
`"build": {
    "linux": {
      "artifactName": "TestApp",
      "target": "AppImage"
    }`

Please let me know if you need any other information. I'd be hugely grateful if you could tell where to find the information needed. 

Cheers

**Comment by megahertz** [comment]
@arvindrajan92 Do you use webpack? If so, check my recommendations above.

**Comment by Crazie-ash** [comment]
![Screenshot from 2019-04-25 14-22-14](https://user-images.githubusercontent.com/45698249/56722881-8c04e680-6765-11e9-8680-5f9c0c070bd8.png)
Is there any fix for this issue????

**Comment by megahertz** [comment]
@Crazie-ash It seems your app is not packaged
