### ISSUE TITLE
electron-simple-updater is not initialized

### ISSUE THREAD

**Issue by debelop13** [megahertz/electron-simple-updater#24]
I have ember electron app compiled with electron-forge.

I run with your example.. and  console is showing "electron-simple-updater is not initialized", what is going on?

Andd when I run checkforupdates.. it shows "update is disabled" without any error.. 

Also, I put disabled to false, and neither is not working

updater.init({
  checkUpdateOnStart: false,
  autoDownload: false,
  disabled: false,
});

In package.json

  "updater": {
    "url": "https://raw.githubusercontent.com/megahertz/electron-simple-updater/master/example/updates.json"
  },

Thanks!!

**Comment by megahertz** [comment]
Check what `app.getName()` returns. It should not be 'Electron'.

**Comment by megahertz** [comment]
Alos, it is disabled automatically for win/mac app store

**Comment by debelop13** [comment]
app.getName returns undefined.. 
updater.version or updater.buildId also returns undefined..

Is not initializing in my main.js ..

**Comment by debelop13** [comment]
If I execute your example like this "electron app/main.js" also is not initializing..  why?

**Comment by megahertz** [comment]
@debelop13 Update can work only for a compiled application
