### ISSUE TITLE
Zip Support? 

### ISSUE THREAD

**Issue by vasyl-shumskyi** [megahertz/electron-simple-updater#25]
Hey there! 

Does updater support zipped  dmg's for bandwidth saving and overall downloading speedup?  
Zipped version of the app usually takes around 30% of the binary size.

----
Oh, i see. Its hidden here: https://github.com/megahertz/electron-simple-updater/releases/download/darwin-x64-prod-v0.0.2/release.json Quick question then: which version has downloading priority in such case: zipped or binary?

**Comment by megahertz** [comment]
dmg for installer and zip for updates

**Comment by cinder92** [comment]
what this means? i need mandatory have two files for update? an `.app` and `.dmg` in server?

**Comment by megahertz** [comment]
Dmg is used only for the first install, zip - for updates

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
