### ISSUE TITLE
always receiving a 'warn' when check for updates

### ISSUE THREAD

**Issue by cinder92** [megahertz/electron-simple-updater#26]
Hello, i just signed my app successfully, i created 2 apps, one with an alert, and one `update` without that alert, but when i open first app my log say this.

![captura de pantalla 2017-06-15 a la s 12 17 36](https://user-images.githubusercontent.com/4725556/27193527-bff2ddde-51c4-11e7-8247-53250859a8ef.png)

and downloading never ends...

is there any fix for this?

Electron V 1.6.6
Electron-simple-updater V 1.2.1

UPDATE

well i figured out that my app was not signed correctly, but now, when downloading starts, then ends, i receive same error.. :(

**Comment by cinder92** [comment]
is not working in `localhost` neither in `remote host`

**Comment by megahertz** [comment]
I can suggest:
- Install electron-log and pass it as the logger options for init(). You'll see detailed error information
- Use electron-simple-publisher to create updates.

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
