### ISSUE TITLE
replacing files

### ISSUE THREAD

**Issue by cinder92** [megahertz/electron-simple-updater#28]
hello this package is not replacing files on windows...

any fix?

**Comment by megahertz** [comment]
Hi. Please provide more information like logs, updates.json content and so on

**Comment by cinder92** [comment]
thanks for response, i just figured out that in the `zip package` you need to put `true` to this value.

```
var zip = new Zip(this.update.file);
zip.extractAllTo(AppPath, true);
```

and tadda!

**Comment by megahertz** [comment]
electron-simple-updater doesn't do update by itself. On windows, it's just initialize Squirrel.Windows with a correct url. Squirrel.Windows does downloading and file replacing.
