### ISSUE TITLE
Updates will not install if app is already initialized

### ISSUE THREAD

**Issue by matthew-dean** [megahertz/electron-simple-updater#31]
I've discovered that if you:

a) Install an app
b) publish an app update while the app is still running
c) check for updates (without restarting app)

...then the updates will never install. It seems that if it receives a 404 the first time, it will never check again to see if subsequent update checks are valid.

**Comment by matthew-dean** [comment]
Never mind my build settings were incorrect.

**Comment by jdiazSitek** [comment]
@matthew-dean What was your build error?

**Comment by matthew-dean** [comment]
@jdiazSitek I had the wrong FTP settings in the publisher JSON file, essentially. So, it was the wrong remote endpoint that it was checking.
