### ISSUE TITLE
can not find squirrel

### ISSUE THREAD

**Issue by manpreetrsystems** [megahertz/electron-simple-updater#34]
I am getting an error while clicking the install button as"can not find squirrel" and the next log message i.e. downloading the update from the url is  displayed but the update doesn't gets downloaded.

**Comment by megahertz** [comment]
Did you install your app?

**Comment by manpreetrsystems** [comment]
I used electron packager for making .exe file.
After running  that exe and clicking for install update it is showing the same error message.

**Comment by megahertz** [comment]
It's not an installer. You need to make an installer with electron builder.

**Comment by manpreetrsystems** [comment]
ok. Thanks alot..

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
