### ISSUE TITLE
[Question] Does simple updater support Enterprise GitHub?

### ISSUE THREAD

**Issue by theuniverse** [megahertz/electron-simple-updater#35]
Currently, our team is using electron-simple-updater perfectly to update the production release. But the problem occurs when we wants to have a new development channel which hosts release on Enterprise GitHub. 

Does anyone know if this project supports Enterprise GitHub?
Thanks in advance.

**Comment by megahertz** [comment]
I've never used GitHub Enterprise. But the only one requirements for updater is possibility to access hosted updates.json from your app. But I'm not sure about publisher.

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
