### ISSUE TITLE
error when updating

### ISSUE THREAD

**Issue by Custardcs** [megahertz/electron-simple-updater#36]
Hi so i finally managed with your help and some figuring out got the updates and publishing to work the way i need.

here is my config

> setText('version', updater.version);
> setText('build', updater.buildId);
> 
> updater.checkForUpdates();
> 
> 
> updater.on('update-available', onUpdateAvailable);
> updater.on('update-not-available', onUpdateNotAvailable)
> updater.on('update-downloading', onUpdateDownloading);
> updater.on('update-downloaded', onUpdateDownloaded);
> updater.setOptions('logger', {
>     info(text) { log('info', text); },
>     warn(text) { log('warn', text); }
> });
> function onUpdateNotAvailable(){
>     console.log("SHOULD ALLOW USER TO LOGIN/OFFLINE OR ONLINE");
> }
> function onUpdateAvailable(meta) {
>     setText('new-version', meta.version);
>     setText('description', meta.readme);
>     console.log("SHOULD STOP USER FROM LOGIN AND UPDATE");
>     updater.downloadUpdate();
> }
> function onUpdateDownloading() {
>     console.log("SHOULD SHOW USER DOWNLOADING");
> }
> function onUpdateDownloaded() {
>     console.log("SHOULD INSTALL AND CHECK AGAIN");
>     updater.quitAndInstall();
> }
> //logger
> function log(level, text) {
>     console.log(`[${level}] ${text}`);
> }
> //text
> function setText(id, text) {
>     console.log(`[${id}] ${text}`);
> }

once the app starts here is the log from the console.

> version 0.0.4
> index.js:45 build win32-x64-prod-v0.0.4
> index.js:41 [info] Found version 0.0.5 at https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.5
> index.js:45 new-version 0.0.5
> index.js:45 description undefined
> index.js:30 SHOULD STOP USER FROM LOGIN AND UPDATE
> index.js:34 SHOULD SHOW USER DOWNLOADING
> index.js:41 [info] Downloading updates from https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.5
> index.js:41 [info] Found version 0.0.5 at https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.5
> index.js:45 new-version 0.0.5
> index.js:45 description undefined
> index.js:30 SHOULD STOP USER FROM LOGIN AND UPDATE
> index.js:34 SHOULD SHOW USER DOWNLOADING
> index.js:41 [info] Downloading updates from https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.5
> index.js:34 SHOULD SHOW USER DOWNLOADING
> index.js:41 [info] Downloading updates from https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.5
> index.js:34 SHOULD SHOW USER DOWNLOADING
> index.js:41 [info] Downloading updates from https://github.com/Custardcs/FilmplicityReleases/releases/download/win32-x64-prod-v0.0.5
> 3index.js:41 [warn] Error: Command failed: 4294967295
> System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
>    at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
>    at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Update.Program.<Update>d__5.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Squirrel.Update.Program.executeCommandLine(String[] args)
>    at Squirrel.Update.Program.main(String[] args)
>    at Squirrel.Update.Program.Main(String[] args)
> ---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running
>    at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
>    at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Update.Program.<Update>d__5.MoveNext()<---

i got a few questions why does it hit into the

 SHOULD SHOW USER DOWNLOADING

so many times?

**Comment by megahertz** [comment]
Check that you've disabled checkUpdateOnStart and autoDownload options when calling init()

**Comment by Custardcs** [comment]
i placed it in the package.json, but if i wanted to place it in the init method?

would it be

updater.int(autoDownload ='false',checkUpdateOnStart='false',url='url);

**Comment by megahertz** [comment]
it's possible to place it in package.json, but first of all, try to pass it to init. Check the package example.

**Comment by Custardcs** [comment]
shot bud. im going to update and test now.

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
