### ISSUE TITLE
Darwin

### ISSUE THREAD

**Issue by Custardcs** [megahertz/electron-simple-updater#38]
updates are working on windows but when i run the same code on mac it stuck on downloading updates from(url)

its not throwing any issues or errors

**Comment by megahertz** [comment]
do you sign your build?

**Comment by Custardcs** [comment]
i created a self signed cert and it found it but it still says its not signed?

**Comment by megahertz** [comment]
You should use Developer ID certificate issued by Apple.

**Comment by Custardcs** [comment]
sweet thanks bro. looks sorted is there no other way other than.... going thru apple?

**Comment by Custardcs** [comment]
how do you catch a request time out?

**Comment by megahertz** [comment]
There is not logic for request timeout. If you implement complex update logic you need to catch request timeout by yourself.

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
