### ISSUE TITLE
Merge into electron-auto-updater (or vice versa)

### ISSUE THREAD

**Issue by develar** [megahertz/electron-simple-updater#4]
electron-builder default target for windows now NSIS and electron-auto-updater was implemented — https://github.com/electron-userland/electron-builder/tree/master/nsis-auto-updater (https://github.com/electron-userland/electron-builder/wiki/Auto-Update)

As far I see in your project you did great job:

* It seems your module allows to avoid special server for macOS? 
* And you already support auto-update on Linux (AppImage)?

These task are planed to be implemented in the electron-builder. But I don't want to reinvent the wheel :)

Maybe you can help me to merge your excellent module into `electron-auto-updater`? Or maybe better just support `electron-simple-updater` in the electron-builder? 

Well, finally, I will "steal" all your ideas and will implement it in the `electron-auto-updater`, but maybe some cooperation will be better :) 

What do you think?

Привет из Германии ;)

**Comment by develar** [comment]
Or maybe I will just reuse your module (as dependency) in the electron-builder to handle macOS/Linux.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/1089

**Comment by megahertz** [comment]
I'm going to support this package, but I'm glad that this idea was helpful for electron-updater.
