### ISSUE TITLE
Auto-update with bitbucket project. Some general questions and issues.

### ISSUE THREAD

**Issue by mikehchuck** [megahertz/electron-simple-updater#41]
Hey guys I am trying to get this to work with my electron app that's on bitbucket.

Concerning the two lines of code that is placed in at the entry point of the app, I'm assuming i should be using my own updates.json file, instead of the one they're providing correct?

In my updates.json file, it says it should be pointing to a zipped .app file. Can this be uploaded to the bitbucket project, and taken from there when updating, or do I need to have that file on a server? I guess the confusion comes from the word "hosting" in step 3, not sure if that means a server or my bitbucket project, or something else

Let me know what you guys think.

Thanks!
Michael

**Comment by megahertz** [comment]
Hi.

It's possible to host an application on bitbucket, but you need to create all necessary files like updates.json and release.json (for mac) with all links manually, because electon-simple-publisher doesn't support bitbucket. And I think you can use only public repository for this purpose.
