### ISSUE TITLE
On Windows, can' open app, updater failing. 

### ISSUE THREAD

**Issue by tjoye20** [megahertz/electron-simple-updater#42]
On Windows, the updater is erroring out and keeping the app from even being opened. 

Below is the log of the error:
[error.txt](https://github.com/megahertz/electron-simple-updater/files/1246376/error.txt)

Here's my setup in the app: 
const updater = require('electron-simple-updater');
function onUpdateDownloaded() {
  updater.quitAndInstall();
}
updater.init()
updater.on('update-downloaded', onUpdateDownloaded);

Can you help me determine what the problem is?

**Comment by tjoye20** [comment]
Windows notifies me that this is part of the reason it's failing:
https://support.microsoft.com/en-us/help/2715633/shim-errors-for-the--net-framework-version-and-platform-support

**Comment by megahertz** [comment]
It seems that it's an internal Squirrel.Windows problem. First of all, try to make a build using the latest electron-builder and electron-builder-squirrel-windows

**Comment by megahertz** [comment]
Try to disable antivirus 
https://github.com/Squirrel/Squirrel.Windows/issues/698

or you can try to google "Couldn't write out staging user ID, this user probably shouldn't get beta anything"

**Comment by tjoye20** [comment]
That's what I did as soon as I posted this, a new npm install, and rebuild. Everything worked fine after that. Thank you.
