### ISSUE TITLE
Cannot find module 'electron-simple-updater'

### ISSUE THREAD

**Issue by marvi14** [megahertz/electron-simple-updater#43]
**Uncaught Exception:
Error: Cannot find module 'electron-simple-updater' at Module._resolveFilename (module.js:470:15)**

This is thrown after I run the app. Any ideas why this is happening?

**Comment by megahertz** [comment]
The problem is outside the package
- check your package.json dependencies
- check webpack config (if it's used)
- check electron-builder config

**Comment by marvi14** [comment]
I already installed the library and add the code as it's mentioned on the [link](https://www.npmjs.com/package/electron-simple-updater). Everything else is working fine, but when getting this library, is throwing the exception.

Checked all you've mentioned, and seems to be ok :(

**Comment by megahertz** [comment]
Check whether the compiled application contains this module at the archive YourApp.app/Contents/Resources/app.asar:node_modules/electron-simple-updater

**Comment by marvi14** [comment]
It's an Angular 4 application, so everything is bundled with Webpack. I really don't know if there is in there, but in case it's not...how do you suggest I fix it? because, the rest of the libraries such as "electron" is beeing bundled and I didn't touch my webpack config to make it work, just did "npm i electron"

**Comment by megahertz** [comment]
Do you use npm5?

**Comment by marvi14** [comment]
No. It's 3.10

**Comment by megahertz** [comment]
I can only suggest you to check whether the package.json contains electron-simple-updater in dependencies section and you've set corresponding webpack target property for electron. If it's ok I can't help you without configs code.

**Comment by marvi14** [comment]
Ya, it's in both...dependencies and devDependencies. I really don't know what's happening. This is my package.json

`{
  "name": "test",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
...
    "build-electron-osx": "ng build --base-href ./ && cp src/electron/* dist",
    "electron-osx": "npm run build-electron-osx && electron dist",
    "build-electron-windows": "ng build --base-href . && copy src\\electron\\* dist",
    "electron-windows": "npm run build-electron-windows && electron dist"
  },
  "private": true,
  "dependencies": {
...
    "electron-simple-updater": "^1.2.0",
...
  },
  "devDependencies": {
...
    "electron": "^1.7.5",
    "electron-builder": "^19.27.7",
    "electron-simple-updater": "^1.2.0",
    "electron-winstaller": "^2.6.3",
...
  }
}`

**Comment by megahertz** [comment]
What's about default webpack config? I need to know the target property.

**Comment by marvi14** [comment]
I was adding the dependencies on the root package.json, not on my src/electron/package.json

**Comment by megahertz** [comment]
Sorry, it's not possible to show progress

**Comment by marvi14** [comment]
Ok. Now I'm having another issue. I'm creating the .exe with `electron-builder -w`. After the download start event is fired, I got this error.

![error](https://user-images.githubusercontent.com/10942833/30398722-c7c9149a-98a7-11e7-8acf-a187e3089446.png)

Do you know how to solve this issue?

**Comment by megahertz** [comment]
I can assume that you use a default NSIS target

**Comment by marvi14** [comment]
Ya I did. It's wrong? How do I need to build to make this auto update working?

**Comment by megahertz** [comment]
You need to set squirrel target. Check electron-builder docs.

**Comment by megahertz** [comment]
Feel free to reopen this issue if your problem is not solved.
