### ISSUE TITLE
Unable get any response on Call back (Issue Or Question)

### ISSUE THREAD

**Issue by vjijardar** [megahertz/electron-simple-updater#45]
Hey,
I didn't get any call back response after updater Init, error, update avail etc
Please Give me Suggestion I'm Using Angular 4 and for update Squirrel.Windows 
Platform is Windows Machine Only

`const updater = require('electron-simple-updater');
updater.init({
  checkUpdateOnStart: true,
  autoDownload: false,
  url:"urlHere"
});

updater.checkForUpdates();
updater.on('checking-for-update',checkUpdate);
updater.on('update-available', UpdateAvailable);
updater.on('update-not-available', onUpdateNotAvailable)
updater.on('error', updateError);

function updateError() {
console.log('error');
}
function onUpdateNotAvailable() {
console.log('No update');
}
function UpdateAvailable() {
console.log('update Avail');
}
function checkUpdate() {
console.log('checkUpdate');
}`

I use this in main.js

**Comment by megahertz** [comment]
Hi. Do you run your app through installer?

**Comment by ervijjusty** [comment]
Hello megahertz,
Yes I'm package the app using  squirrel-windows.

**Comment by megahertz** [comment]
It's strange. 

Please print the output of
```js
const updater = require('electron-simple-updater');
console.log(updater.options);
```

**Comment by vjijardar** [comment]
Hey,
I got Below Response to log the options

{"autoDownload":true,"build":"","channel":"prod","checkUpdateOnStart":true,"disabled":false,"empty":true,"logger":{},
"version":"","url":""}

**Comment by megahertz** [comment]
Thanks. And please print the output after initialization
```
const updater = require('electron-simple-updater');
updater.init({
  console,
  checkUpdateOnStart: true,
  autoDownload: false,
  url:"urlHere"
});
console.log(updater.options);
```

**Comment by vjijardar** [comment]
I got same response but also  got new log is **Update is disabled**

**Comment by megahertz** [comment]
and what is the result of `app.getName()?`

**Comment by vjijardar** [comment]
yeah its print **Electron** but in my package.json i'll given its my name is **Digi******

**Comment by megahertz** [comment]
In the most cases it happens when an application is not built correctly through electron-builder

**Comment by vjijardar** [comment]
yes but i think the application successfully build with like name with Digi***-win32-ai32/Digi***.exe and its run without error. i dont know what is going wrong.

**Comment by megahertz** [comment]
it should be Digi*** Setup ***.exe

**Comment by megahertz** [comment]
the app you run is not a squirrel-installed application

**Comment by vjijardar** [comment]
No I'm package the app using eletron-packger after that i'll use the eletron winstaller in package.json
Have a Look
```
"build-electron": "ng build --base-href . && copy main.js dist",
    "start": "npm run build-electron && electron dist/main.js",
    "package-windows": "npm run build-electron && electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --prune=true --out=release-builds Digirecord  --icon=assets/icons/win/icon.ico --win32metadata.CompanyName='Digiscribe Technology Pvt Ltd' --win32metadata.ProductName=Digirecord --win32metadata.FileDescription='Digiscrice Technology ' --appCopyright='Copyright © 2017 Digirecords Powerd by Digiscribe Technology Pvt Ltd Inc. All rights reserved.'",
    "create-installer-windows": "node installer/windows/createinstaller.js",
    "full-build-windows": "npm run build-electron && npm run package-windows && npm run create-installer-windows",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
```
and installer is 
```
const createWindowsInstaller = require('electron-winstaller').createWindowsInstaller
const path = require('path')

getInstallerConfig()
     .then(createWindowsInstaller)
     .catch((error) => {
     console.error(error.message || error)
     process.exit(1)
 })

function getInstallerConfig () {
    console.log('creating windows installer')
    const rootPath = path.join('./')
    const outPath = path.join(rootPath, 'release-builds')
console.log("root"+rootPath);
    return Promise.resolve({
       appDirectory: path.join(outPath, 'Digirecord-win32-ia32/'),
       title:'Digirecords',
       authors: 'Digiscribe Technology Pvt Ltd',
       noMsi: false,
     // loading_gif: path.join(rootPath, 'loader.gif'),
      outputDirectory: path.join(outPath, 'windows-installer'),
       exe: 'Digirecord.exe',
       setupExe: 'Digirecord.exe',
       setupIcon: path.join(rootPath, 'assets', 'icons', 'win', 'icon.ico')
   })
}
```
and the output are 
![screenshot 34](https://user-images.githubusercontent.com/19422534/31481927-64ff5588-af43-11e7-99e7-af7cc3e3c5a2.png)
![screenshot 35](https://user-images.githubusercontent.com/19422534/31481931-6551d56a-af43-11e7-88ba-e18321999b04.png)

I think so that is error is coming from electron-packager .

So solution is build using Electron-builder its not working with electron-packager .

**Comment by megahertz** [comment]
Yes, I didn't use electron-packager with electron-winstaller and I don't know if that build can use ESU. Just to be sure:
- add code which prints app.getName() in your app
- build a distributive
- install through DigirecordsSetup.msi on your computer
- run installed version and check what app.getName() prints, 'Electron' or 'Digirecords'.

**Comment by vjijardar** [comment]
hey Megahertz,

I'm trying to build using Electron-builder and Run updater after that.  and Let u know if any issue i'm getting in updater. ill back after 1 week. i'll close its right now.

Thanks for support.
