### ISSUE TITLE
Linux updater checks that AppImage file is writable, but we care only about directory permissions

### ISSUE THREAD

**Issue by dchest** [megahertz/electron-simple-updater#46]
Here access call checks with W_OK that the file is writable:

https://github.com/megahertz/electron-simple-updater/blob/master/lib/linux.js#L47

However, since `fs.rename` call is used to *replace the file* (write to directory entry, not to the file), it doesn't actually care that the file is writable by the current user — only directory permissions matter here. Even if the file is not writable, but the directory is writable, the file can be replaced.

Two ways to fix it:

1. Check that the file exists with F_OK (instead of W_OK), and handle fs.rename error later.
2. Check that path.dirname(appImagePath) is writable instead of appImagePath (this can be done in addition to 1).

**Comment by megahertz** [comment]
Thank you. Actually, there was write permission check for the path in getTemporaryFilePath().
