### ISSUE TITLE
Update failing with "Could not read desktop shortcut in AppImage"

### ISSUE THREAD

**Issue by rajendra2** [megahertz/electron-simple-updater#47]
Update used to work fine with earlier appimages generated by earlier versions of electron-builder (<= 19.33.0).
But electron-simple-updater is not able to find desktop shortcut data ([Desktop Entry]) in the appimages generated by newer version of electron-builder (failed with electron-builder version 19.34.2)

I extracted the content of newer appimages and the desktop file does exist with "[Desktop Entry]". Maybe some change is needed in electron-simple-updater to be compatible with newer appimages.

**Comment by megahertz** [comment]
Thank you. Since systemIntegration option was added to electron builder, desktop file patching is not necessary. Fixed.
