### ISSUE TITLE
Why beta channel don't check for releases?

### ISSUE THREAD

**Issue by debelop13** [megahertz/electron-simple-updater#48]
Hi!

I think that beta channel should can to update to a release,

exists any way for achieve this? or to do in my app?

much thanks!

**Comment by megahertz** [comment]
You can point to release files in beta section of updates.json. But in this case, it will receive only production builds later.

**Comment by debelop13** [comment]
yes, but it would not be better like to change between beta and release if user wants?

like option to check for beta updates or not

**Comment by megahertz** [comment]
Sorry, but I'm not going to add this feature. When I thought about channel architecture, I've decided that each channel should work independently. So only way to switch between prod and beta channel - install the corresponding build.

**Comment by debelop13** [comment]
Okey!

I am setting the channel with setOptions depends user wants a release or beta updates. 

Thanks!

**Comment by megahertz** [comment]
Does it work correctly?

**Comment by debelop13** [comment]
yes! 

if (enabledBetaAutoupdate) {    // Check for BETA updates
   updater.setOptions('channel', 'beta');
   updater.checkForUpdates();
}

sorry for the lateness

**Comment by megahertz** [comment]
Thank you for feedback!
