### ISSUE TITLE
Change darwin update format

### ISSUE THREAD

**Issue by MrBlenny** [megahertz/electron-simple-updater#5]
The update link for Darwin is specified as follows:
```
  "darwin-x64-prod": {
    "update": "https://github.com/megahertz/electron-simple-updater/releases/download/example-darwin-x64-prod-v0.0.2/release.json",
    "version": "0.0.2",
    "platform": "darwin",
    "readme": "Second version"
  }
```

Is it possible to change the:
update: `XXXX/XXXX/XXXX/release.json`  to `XXXX/XXXX/XXXX/MyApp-0.0.11-mac.zip`?

The electron-builder does not seem to produce a release.json for me so it has to be created manually. In any-case, release.json it does not seem to provide any useful meta except for the url.

**Comment by megahertz** [comment]
Unfortunately, Squirrel.Mac requires this file. You can use electron-simple-publisher to generate this file automatically.

**Comment by megahertz** [comment]
I've checked again and there is no way to simplify it.

**Comment by develar** [comment]
> The electron-builder does not seem to produce a release.json for me

https://github.com/electron-userland/electron-builder/issues/1089
