### ISSUE TITLE
can not get update!

### ISSUE THREAD

**Issue by jackple** [megahertz/electron-simple-updater#52]
I publish an app with version 1.0.4 in package.json, when I use electron-simple-updater, I make the updates.json like:
{
    "win32-x64-prod": {
        "readme": "日常更新",
        "update": "https://xxxx/worker-management/1520414279",
        "install": "https://xxxx/worker-management/1520414279/%E4%BC%8A%E4%BA%91%E4%BB%93TEM%20Setup%201.0.5.exe",
        "version": "1.0.5"
    }
}

I run this script to pack:
`
"pack:win": "electron-builder --win --ia32"
`
my update url is
`
"updater": {
        "url": "http://xxxx/worker-management/raw/master/updates.json?private_token=xxxx"
 }
`

in main.js

updater.init({
    checkUpdateOnStart: false,
    autoDownload: false
})

in render.js:

import { remote } from 'electron'
export default function update() {
    const updater = remote.require('electron-simple-updater')
    updater.on('update-available', meta => {
        console.log('[updater] update avaiable', meta.version)
        updater.downloadUpdate()
    })
    updater.on('update-not-available', () => {
        console.log('there is no available update')
    })
    updater.on('update-downloading', () => {})
    updater.on('update-downloaded', () => {
        if (window.confirm('Restart and install updates?')) {
            updater.quitAndInstall()
        }
    })
    updater.on('error', err => {
        console.warn(err)
    })
    updater.checkForUpdates()
}

I always got 'there is no available update'.
What is wrong with my case?

**Comment by megahertz** [comment]
1. Make sure that you 1.0.5 is published successfully (with exact version 1.0.5 in package.json)
2. Make sure that you run 1.0.4 to test updates (also, with exact version 1.0.4 in package.json)
3. Show application logs (run compiled app from console or use electron-log instead of console.log)

**Comment by jackple** [comment]
@megahertz I have uploaded three file like:
![image](https://user-images.githubusercontent.com/6183232/37086077-a6ee96f0-2231-11e8-947f-043e29c7346f.png)

**Comment by jackple** [comment]
@megahertz I get the error "Can not find Squirrel", but I do not find some ways to fix it. Can you help?

**Comment by megahertz** [comment]
@jackple https://github.com/electron/electron/issues/4535

**Comment by jackple** [comment]
@megahertz I saw this issue, but I do not know how to fix it

**Comment by megahertz** [comment]
Check your build config, for example https://github.com/megahertz/electron-simple-updater/blob/master/example/package.json

**Comment by jackple** [comment]
@megahertz 
"updater": {
        "url": "http://xxxxxx/-worker-management/raw/master/updates.json?private_token=xxxxx"
    },
    "build": {
        "productName": "伊云仓TEM",
        "appId": "com.worker-management",
        "directories": {
            "output": "package"
        },
        "files": [
            "dist/production/",
            "node_modules/",
            "package.json",
            "index.js",
            "index.html"
        ],
        "dmg": {
            "contents": [
                {
                    "x": 410,
                    "y": 150,
                    "type": "link",
                    "path": "/Applications"
                },
                {
                    "x": 130,
                    "y": 150,
                    "type": "file"
                }
            ]
        },
        "mac": {
            "icon": "src/assets/icons/icon.icns",
            "category": "public.app-category.utilities",
            "target": [
                "dmg"
            ]
        },
        "win": {
            "icon": "src/assets/icons/icon.ico",
            "target": [
                "nsis",
                "squirrel"
            ]
        },
        "squirrelWindows": {
            "iconUrl": "https://xxxx/uploads/icon.ico"
        }
    }

I can not see what is the problem with my config

**Comment by jackple** [comment]
@megahertz the error like that:
![image](https://user-images.githubusercontent.com/6183232/37137695-e65068cc-22e1-11e8-9a27-4ee505b1ed72.png)
![image](https://user-images.githubusercontent.com/6183232/37137697-e9d82426-22e1-11e8-80d1-6abbe6413c88.png)

**Comment by megahertz** [comment]
First of all, disable nsis and rebuild the application for both 1.0.4 and 1.0.5

**Comment by jackple** [comment]
@megahertz thank you so much! I added the "nsis" option because I though that user must install the app(producted by nsis) at the first time, but it is not.

**Comment by jackple** [comment]
@megahertz It was successfully when I installed 1.0.0 and I updated to 1.0.1, but I got error when I tried to update to 1.0.2.

Error: Command failed: 4294967295
System.AggregateException: ����һ���������� ---> System.Exception: Checksummed file size doesn't match: C:\Users\ERP\AppData\Local\worker-management\packages\worker-management-1.0.12-full.nupkg
   �� Squirrel.UpdateManager.DownloadReleasesImpl.checksumPackage(ReleaseEntry downloadedRelease)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<Update>d__5.MoveNext()
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   �� System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   �� System.Threading.Tasks.Task.Wait()
   �� Squirrel.Update.Program.executeCommandLine(String[] args)
   �� Squirrel.Update.Program.main(String[] args)
   �� Squirrel.Update.Program.Main(String[] args)
---> (�ڲ��쳣 #0) System.Exception: Checksummed file size doesn't match: C:\Users\ERP\AppData\Local\worker-management\packages\worker-management-1.0.12-full.nupkg
   �� Squirrel.UpdateManager.DownloadReleasesImpl.checksumPackage(ReleaseEntry downloadedRelease)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<Update>d__5.MoveNext()<---





    at AutoUpdater.emitError (C:\Users\ERP\AppData\Local\worker-management\app-1.0.11\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.update (C:\Users\ERP\AppData\Local\worker-management\app-1.0.11\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:43:23)
    at ChildProcess.<anonymous> (C:\Users\ERP\AppData\Local\worker-management\app-1.0.11\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by megahertz** [comment]
It seems that your build is corrupted.

**Comment by Crazie-ash** [comment]
i using windows target as portable.... it works till updater.on('update-downloaded') and then no response.. cannot find y???
But it works with linux!!!!

**Comment by megahertz** [comment]
@Crazie-ash No it doesn't works with portable build. https://github.com/electron-userland/electron-builder/issues/3508

**Comment by Crazie-ash** [comment]
I tried but Error: Can not find Squirrel... i don't what i am missing!!!

**Comment by megahertz** [comment]
@Crazie-ash I think electron-builder and electron-builder-squirrel-windows should have the same version. Anyway, I can't help you too much with the build problem.

**Comment by Crazie-ash** [comment]
As u said i tried using the same version. it worked well but i am still facing this Error: Can not find Squirrel

I am using the following
updates.json
{
  "win32-x64-prod": {
    "update": "http://"myip"/bbUpdate/windows/exe",
    "install": "http://"myip"/bbUpdate/windows/exe/biggbossSetup1.0.1.exe",
    "version": "1.0.1"
  }
}
------------------------------------------------------------------------------------
package.json
"electron-builder-squirrel-windows": "20.39.0",
"electron-builder": "20.39.0",
------------------------------------------------------------------------------------
electron-builder.json
 "win": {
      "icon": "dist/assets/favicon.256x256.png",
      "target": [
      "squirrel",
      "zip"
    ]},
    "squirrelWindows": {
      "iconUrl": "https://raw.githubusercontent.com/megahertz/electron-simple-updater/master/example/build/icon.ico"
    },
----------------------------------------------------------------------------------------
update path folder "/bbUpdate/windows/exe/" contains the following

biggboss-1.0.1-win.zip
biggbossSetup1.0.1.exe
biggbossSetup1.0.1.nupkg
builder-effective-config.yaml
RELEASES

**Comment by megahertz** [comment]
@Crazie-ash You can see such a message only when you run non squirrel build.
