### ISSUE TITLE
download-progress

### ISSUE THREAD

**Issue by Custardcs** [megahertz/electron-simple-updater#53]
hi I see the default electron uses  this can we access this method through yours?

autoUpdater.on('download-progress', (progressObj) => {

// })

**Comment by megahertz** [comment]
Could you provide a link to this information? As I know, electron-updater supports this feature, but not the built-in module.

**Comment by Custardcs** [comment]
![screen shot 2018-03-23 at 10 11 47](https://user-images.githubusercontent.com/14811199/37818408-bf5394fe-2e82-11e8-9d99-38207dfd79e8.png)
as you can see it says its part of builder?

maybe I miss understand but it seems to be together...

**Comment by megahertz** [comment]
Yes, it's a subproject of electron-builder, but not of electron
