### ISSUE TITLE
download-progress

### ISSUE THREAD

**Issue by LonelystartO** [megahertz/electron-simple-updater#54]
When I use electron-builder on linux platform , there was no download-progress event.For example, I can use `updater.on('download-progress')` to show the downloading progress. Could you please add the function someday? thanks.

**Comment by megahertz** [comment]
Unfortunately, it's not very easy to implement download-progress for all platforms without complex tricks. Sorry, but it's better to migrate to [electron-updater](https://www.npmjs.com/package/electron-updater) if you need this feature.
