### ISSUE TITLE
Error when try to download update

### ISSUE THREAD

**Issue by huangxuewu** [megahertz/electron-simple-updater#55]
Here is the error message:

Error Message: Error: Command failed: 4294967295
System.AggregateException: ����һ���������� ---> System.Net.WebException: ������ֹ: ���ӱ�����رա�
   �� System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   �� System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   �� Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   �� System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   �� System.Threading.Tasks.Task`1.get_Result()
   �� Squirrel.Update.Program.executeCommandLine(String[] args)
   �� Squirrel.Update.Program.main(String[] args)
   �� Squirrel.Update.Program.Main(String[] args)
---> (�ڲ��쳣 #0) System.Net.WebException: ������ֹ: ���ӱ�����رա�
   �� System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   �� System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   �� Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---

above is the error trigger by updater.downloadUpadte()

any help is much appreciate!
BTW does anyone know where the download file path is?

**Comment by huangxuewu** [comment]
Problem fixed. Close this.

**Comment by ankitsomani007** [comment]
What was your issue? I had same issue

**Comment by megahertz** [comment]
@ankitsomani007 It seems there is some network issue
