### ISSUE TITLE
unable to find electron app

### ISSUE THREAD

**Issue by HappyGod158** [megahertz/electron-simple-updater#59]
when I run the example, first  install with npm :
```
 npm install 
```
then run the script: 
```
npm start
```
an error happened as follow: 

![tim 20181122143146](https://user-images.githubusercontent.com/13306414/48885479-69436e80-ee63-11e8-8323-942f41a612ce.png)

**Comment by megahertz** [comment]
Thank you, I'll fix it a bit later. At this moment, you can change start script in a package.json to "start": "electron .",

**Comment by HappyGod158** [comment]
it works!  Thanks~
