### ISSUE TITLE
Use network share as update source produces Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by samuelcarreira** [megahertz/electron-simple-updater#6]
Hi, first of all, congrats for your great work.

I started a project when I need to use an offline solution on a local network. So I cannot update the apps on my web server. 
When I tried to connect to my network share folder it produces the following error:

> [warn] Error: connect ECONNREFUSED 127.0.0.1:80

I use the following code:
`updater.init('\\\\10.0.1.1\\c\\update');`

The path is correct and with **fs** I can browse the files.
Sample code:
```
const testFolder = '\\\\10.0.1.1\\c\\update';
const fs = require('fs');
fs.readdir(
...
    console.log(file);
...
```

Can you help me?

Thank you

**Comment by megahertz** [comment]
Hi, I'll try to test it later but I think that Squirrel (which is used inside) does not support other than http(s) protocols. And I know exactly that linux updates can be used only through http(s) protocol. Maybe it's easier to setup http service on your internal server?

**Comment by samuelcarreira** [comment]
Thank you for your help. Its a valid point about the squirrel.
I will check if it's possible to create a http server on that device without risking the security of the solution 
Regards

**Comment by megahertz** [comment]
Also you can start a http server on localhost. It will be just like a proxy to SMB resources.

**Comment by megahertz** [comment]
It seems that it's possible (but not very easy) to use SMB as update source with Squirrel.Windows. But I think there is no reason to add this feature in this library. If you want to have only windows updates and store it on SMB, it's better to use the built-in autoUpdater module.
