### ISSUE TITLE
is Squirrel required?

### ISSUE THREAD

**Issue by Liga97** [megahertz/electron-simple-updater#62]
Hi,

I've followed all the steps and i got the message that a new version is available.
Into the console i can see these info:

level: warn - text: Error: Can not find Squirrel
app.js:31 level: info - text: Downloading updates from http://xxxxx.xxxxx.com/validatore-demo-1-Setup-1.2.0.exe

I'm asking if Squirrel is required on the host or not?

Thanks,
Liga

**Comment by megahertz** [comment]
Hi. It seems that your application is packaged not using Squirrel. Maybe you use NSIS target?

**Comment by Liga97** [comment]
Hi @megahertz ,

Thank you for your quick reply.

Yes, I'm using NSIS as following:

"win": {
      "target": [
        "nsis"
      ]
    }

What I'd like to understand is if I need to install  Squirrel on server side or I can use only a static JSON file?

**Comment by megahertz** [comment]
This package supports only squirrel as a target on windows, not nsis. You don't need any server software, static json is enough.

**Comment by megahertz** [comment]
Feel free to reopen if it doesn't work for you.
