### ISSUE TITLE
Enable in develop mode

### ISSUE THREAD

**Issue by dspangenberg** [megahertz/electron-simple-updater#63]
To implement the UI for "update is available" I tried to enable the plugin in develop mode.

No matter what I try – as well in renderer as in main process – it don't work.

Do I miss something or is it simply not possible? 	

```
updater.on('update-available', meta => {
  console.log(meta)
})

```
```
updater.init({
  url: '...',
  disabled: false,
  checkUpdateOnStart: false,
  autoDownload: false
})
updater.checkForUpdates()
```

=> "Update is disabled".

```
updater.init({
  url: '...',
  checkUpdateOnStart: false,
  autoDownload: false
})
updater.setOptions('disabled', false)
updater.checkForUpdates()
```

=> "You must set url before calling checkForUpdates()".

```
updater.init({
  url: '...',
  checkUpdateOnStart: false,
  autoDownload: false
})
updater.setOptions('disabled', false)
updater.setOptions('url', '...')
updater.checkForUpdates()
```
=>  "electron-simple-updater is not initialized"

**Comment by megahertz** [comment]
The module does not work in dev mode. Only in a packaged application.

**Comment by megahertz** [comment]
If you would like to test you UI, you can call `updater.emit('update-available', metaInformation)`. Or set `electron.isPackaged = true` before calling `updater.init()`

But I don't know exactly whether this hack will work :)
