### ISSUE TITLE
No @types/electron-simple-updater

### ISSUE THREAD

**Issue by t00130** [megahertz/electron-simple-updater#66]
I'm having trouble using this package in typescript project due to lack of definition file...

**Comment by megahertz** [comment]
I'm going to add type definition, but that isn't my priority at this moment. Feel free to send me a PR if you need that ASAP.

**Comment by debelop13** [comment]
Hi, 

I don't know if it is the same error

But I have this error when my application tries to update 
"auto-update warnning: TypeError: opt.logger.debug is not a function"

I am using yarn 1.13.0 and node 10.15.2

Two weeks ago was working! And I am compiling the same version (same commit) now and appears this warning.. I don't know if I changed some in my computer (I think that no, and it happens in two computers that i have)

Tell me something if you know!

Thanks

**Comment by megahertz** [comment]
@debelop13 It's not related to this issue. Update to v1.4.4
