### ISSUE TITLE
checkForUpdates not responding

### ISSUE THREAD

**Issue by debelop13** [megahertz/electron-simple-updater#69]
Hello,

I am having problems because calling "checkForUpdates", there are not updates, but i don't get the "updates xxx not available"

My updates.json is like this

> {
  "win32-x64-beta": {
    "readme": "Example 3.2.0-B001",
    "update": "xxx/beta/win32/3.2.0-B001",
    "install": "xxx/beta/win32/3.2.0-B001/Example-3.2.0-B001.exe",
    "version": "3.2.0-B001"
  },
  "darwin-x64-beta": {
    "readme": "Example 3.2.0-B001",
    "update": "xxx/beta/darwin/3.2.0-B001/beta.json",
    "install": "xxx/beta/darwin/3.2.0-B001/Example-3.2.0-B001.dmg",
    "version": "3.2.0-B001"
  },
  "win32-x64-prod": {
...
  },
  "darwin-x64-prod": {
....
  }
}

Thanks!

**Comment by megahertz** [comment]
Hi, do you check it by subscribing to the event, or by viewing logs?

**Comment by debelop13** [comment]
Yes,

Like this,

> 
    updater.on('update-available', meta => {
      this.onUpdateAvailable(meta);
    });
    updater.on('update-downloading', meta => {
      this.onUpdateDownloading(meta);
    });
    updater.on('update-downloaded', meta => {
      this.onUpdateDownloaded(meta);
    });
    updater.setOptions('logger', {
      info(text) {
        log.info(`auto-update: ${String(text)}`);
        if (String(text).includes('is not available')) {
          self.set('message', `Example ${pjson.version} is up to date.`);
        }
      },
      warn(text) {
        log.warn(`auto-update warnning: ${String(text)}`);
        self.set('isDownloading', false);
        self.set('message', 'An error occurred while checking for updates.');
        self.set('error', true);
      }
    });


I haven't change nothing of this method, and I was receiving the message before.

**Comment by megahertz** [comment]
Add a debug method to your logger object

**Comment by debelop13** [comment]
Now I get this

> auto-update debug: Update for darwin-x64-beta-v3.2.0-B001 is not available

**Comment by megahertz** [comment]
so, it can be closed?

**Comment by debelop13** [comment]
Well, the message before was in "info" log
If now it has changed, its ok

**Comment by megahertz** [comment]
Yes, it's new behavior.
