### ISSUE TITLE
Could not create temporary directory

### ISSUE THREAD

**Issue by debelop13** [megahertz/electron-simple-updater#70]
Hello,

I have this warning in one machine:

> "Error: Could not create temporary directory: Permission denied"

It founds a new version, and when is downloading appears this

Do you know why?

Thanks

**Comment by megahertz** [comment]
Hi. There is no such a warning in this lib, so it seems it's squirrel error. Could you provide more information?

**Comment by debelop13** [comment]
hi!

Searching about squirrel and this error i found this:

https://github.com/atom/atom/issues/5160

Using this, works

"$ sudo chown -R $USER ~/Library/Caches/com.electron.Example.ShipIt"

Solved, thanks!
