### ISSUE TITLE
Update often fails on Raspberry Pi

### ISSUE THREAD

**Issue by MartinPavlik** [megahertz/electron-simple-updater#74]
Hi,

I'm having issues with updating electron app that runs on Raspberry Pi. Everything works fine but when the udpated app should be started, the binary is sometimes corrupted and it can not start or some other process is blocking it.

I recieve errors like:
```
Command failed: '/home/pi/app.AppImage.update' --appimage-extract ...
/bin/sh/: 1: /home/pi/app.AppImage.update: Text file busy
```
> Why the .update file needs to be extracted? Does it mean that it simply stops the current process, renames the file to .AppImage and starts it again?

And sometimes the AppImage seems alright, but when it is started it throws segmentation fault `SIGSEGV`.

I guess that the errors are caused by RPI file system, so my question is - is there some way how to detect these errors and retry the update (download the file again?). The weird thing is that when is use `curl`, the file is never corrupted or anything like that. Do you have any ideas what I'm doing wrong?

Thank you :beer:

**Comment by megahertz** [comment]
Hi. Thank you for the report. There are a lot of reasons which can lead to such a problem.

> Why the .update file needs to be extracted? Does it mean that it simply stops the current process, renames the file to .AppImage and starts it again?

AppImage loader shows update confirmation when updated version is started if a Desktop file contains old buildId. So this module patches the Desktop file to update buildId. 

I'm going to investigate this problem on the next week.

**Comment by megahertz** [comment]
@MartinPavlik Sorry for delay. I'm working on this issue now.

**Comment by megahertz** [comment]
@MartinPavlik Try v2.0.0-beta.3. It check sha256 field from updates.json. You can use the latest version of publisher, now it calculates this field automatically.

**Comment by MartinPavlik** [comment]
@megahertz ok thanks, check sums are good idea :+1:
