### ISSUE TITLE
Update is disabled because the app is not packaged

### ISSUE THREAD

**Issue by Nitingadhiya** [megahertz/electron-simple-updater#75]
Hello,
I'm new in electron.js  and have facing issue "Update is disabled because the app is not packaged".
can you please help us how to fix it?

Step 1 : I have clone your git Repo and go to example folder then got to Terminal, run "npm install".
Step 2 : In terminal Run "electron ." command.
Step 3: Face above issue

Thanks.

**Comment by megahertz** [comment]
Hi. Updater works only when your application is packaged using electron-builder and is ready to deliver to end user.

**Comment by Nitingadhiya** [comment]
How can i check auto updater functionality during developing time? @megahertz

**Comment by megahertz** [comment]
Unfortunately, there is no easy way. If you just want to quickly test this feature you need to make a beta build and deploy it to a test server. Than you can perform manual testing.

If you would like to make automated test you need to dive deeper into it. It requires much more time. For example, I use [the project](https://github.com/megahertz/electron-simple-updater/tree/master/test-projects) to test updater on Linux.

**Comment by zhubinsheng** [comment]
i think  it is nessnecessary
esary to Update when the app is not packaged
