### ISSUE TITLE
What should be path of update for windows

### ISSUE THREAD

**Issue by ankitsomani007** [megahertz/electron-simple-updater#77]
I was looking at example updates.json and looking at windows, it look like the update path (https://github.com/megahertz/electron-simple-updater/releases/download/win32-x64-prod-v0.0.2) was leading to empty release on github project. I am not using github, but using s3 to host these builds. What should be path for "update" for windows? 

https://github.com/megahertz/electron-simple-updater/blob/master/example/updates.json

```
"win32-x64-prod": {
    "readme": "Second release",
    "update": "https://github.com/megahertz/electron-simple-updater/releases/download/win32-x64-prod-v0.0.2",
    "install": "https://github.com/megahertz/electron-simple-updater/releases/download/win32-x64-prod-v0.0.2/Simple.Updater.Example.Setup.0.0.2.exe",
    "version": "0.0.2"
  }
```

Note: It works fine for mac since it uses release.json file for update.

**Comment by megahertz** [comment]
It's ok. Squirrel.Windows adds /RELEASE suffix to the path by itself.

**Comment by ankitsomani007** [comment]
Yeah, I works as expected. Thanks!
