### ISSUE TITLE
Add User agent to request

### ISSUE THREAD

**Issue by fp07** [megahertz/electron-simple-updater#78]
Hello,

Would it possible to add the HTTP User-Agent header for an request to the download url?

**Comment by megahertz** [comment]
Hi, at this moment I have no plans to customize HTTP client options, since most of the time static HTTP server / cloud storage is used for update publishing.

**Comment by fp07** [comment]
I understand, but when using an CDN for example Cloudflare the requests are not working, because an empty user agent triggers web application firewall on most servers. @megahertz

**Comment by megahertz** [comment]
Thank you for explaining. I'll add the header a bit later.

**Comment by megahertz** [comment]
Fixed in 2.0.9

**Comment by fp07** [comment]
Thanks for the feature @megahertz really appreciate it!
