### ISSUE TITLE
Simple Updater: The Request was Aborted

### ISSUE THREAD

**Issue by bryantb2** [megahertz/electron-simple-updater#79]
Okay, so here's the situation. I have a private github repo and an application that I was originally packaging for NSIS and win-MSI that I migrated to Squirrel. The updating itself appears to initiate, but blows up about halfway through.

At this point, I have triple checked everything. Currently, I have the updater getting setup in the top level of my application like so: 

```
class AppUpdater {
  constructor() {
    // setup auto-updating
    updater.init({
      checkUpdateOnStart: false,
      autoDownload: false,
      url: process.env.NODE_ENV === 'development' ? process.env.UPDATES_URL_DEVELOPMENT : process.env.UPDATES_URL_PRODUCTION
    });
  }
}
```

The package.json for the build looks like this: 

```
"build": {
    "productName": "ModLEDControl",
    "appId": "org.develar.ModLEDControl",
    "extraFiles": [
      "dotnet/",
      "config.json"
    ],
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
    "nsis": {
      "allowElevation": true
    },
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "requestedExecutionLevel": "highestAvailable",
      "target": "squirrel"
    },
    "linux": {
      "target": [
        "deb",
        "rpm",
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "buildResources": "resources",
      "output": "release"
    }
  }
```

The publisher JSON, which is at the top level (same as package.JSON), looks like this:
```
{
  "transport": {
    "module": "github",
    "token": "example",
    "updatesJsonPath": "modapi-react/updates.json"
  }
}
```

And finally I have the actual update code (I am using React class components, so the update logic is in the lifecycle methods):

```
componentDidMount = () => {
    // check for updates
    // add callbacks to electron updater
    updater.on('update-available', () => {
      this.setState({
        updateAvailable: true
      });
    });
    updater.checkForUpdates();
  }

  componentDidUpdate = () => {
    const { updateInstalling } = this.state;
    if (updateInstalling) {
      // update application and then force a quit/install
      updater.on('update-downloaded', () => {
        console.log('update has been downloaded');
        if (confirm('App has been updated. Would you like to quit and restart now?'))
          updater.quitAndInstall();
      });
      updater.downloadUpdate();
    }
  }
```

Is there any suggestions you might have to resolve my download fetching issue? Again, I am using a private github repo, so it would be great if you could tell me how I ensure that I'm connecting to it with the token system. Thanks!

**Comment by megahertz** [comment]
First of all, it doesn't support private repo out of the box, so make sure all the links updates.json, files pointed by `update` section of updates.json are available.

Also collecting detailed logs of update can be helpful

**Comment by bryantb2** [comment]
Hmmm. I have my updates.json setup correctly. It is currently being served from a local development server. 

Several questions then:

1. What does it mean for the "update section of updates.json to be available"? Currently, the install link will direct to a .exe download, but the update link just results in an "unavailable" page with github, much like your's in the example. Where should the ``update`` property of the updates.json be pointing to, exactly?

2. Is it enough to have my github API key in the publisher JSON, at the top-level of my application, for the updater to automatically access my releases? 

3. How would one go about grabbing detailed logs of update?

**Comment by megahertz** [comment]
1. For windows, update section should point to a directory where RELEASE file is located.
2. No, electron-simple-updater doesn't read publisher.json. github API token in the file is used only for electron-simple-publisher.
3. `updater.init({ logger: require('electron-log') });`

I don't think updates in a private repository could be used directly. All the files necessary for update should be available through a direct unauthorized link.

**Comment by bryantb2** [comment]
So you are saying I'd have to use a public github repo to update my application?

**Comment by megahertz** [comment]
I don't know the way how a private repo could be used. 

RELEASE file is the standard file of Squirrel Windows, you could check the example.

**Comment by megahertz** [comment]
Please open a new issue if you still have some questions.
