### ISSUE TITLE
Cant read property 'on' on undefined

### ISSUE THREAD

**Issue by Pirozek** [megahertz/electron-simple-updater#8]
Hi, I am using your updater and I have problem when I import it, it can't ready properto 'on' on undefined on line 35 of index.js.

I was able to fix it by including autoupdater like this:
```
const electron =  require('electron');
const app = electron.remote.app;
const autoUpdater = electron.remote.autoUpdater;
```

But I would like to know if this is my issue or issue of library. Am I doing something wrong? I have my electron 1.4.7 in devDependecies of project and I don't have it installed globally.

**Comment by megahertz** [comment]
Hi. I'll update this library in a few days and will try to test your scenario. Now you can look at the project's example and how it imports the electron-simple updater. Also, could you provide the code where you import electron-simple-updater and the fragment of index.js where error occurred?

**Comment by Pirozek** [comment]
Including updater like this `const updater = require('electron-simple-updater');` and fragment of index.js that was broken is:

```
   this.meta = {
      empty:     true, // Mark that it's not initialized
      version:   '',
      update:    ''
    };

    autoUpdater.on('update-downloaded', () => { //<== HERE
      const version = this.meta.version;
      this.options.logger.info(`New version ${version} has been downloaded`);
      /**
       * @event SimpleUpdater#update-downloaded
       * @param {object} meta Update metadata
       */
      this.emit('update-downloaded', this.meta);
    });
```

**Comment by megahertz** [comment]
It seems that you import electron-simple-updater in the renderer process directly. If you would like to use this library from renderer process you should import it like this:
const { remote } = require('electron');
const updater = remote.require('electron-simple-updater');

**Comment by uvlek** [comment]
I am trying to use updater in renderer :

**Comment by uvlek** [comment]
const { remote } = require('electron');
const updater = remote.require('electron-simple-updater');
But checkForUpdates - this functions executes from electron updater module

**Comment by megahertz** [comment]
@uvlek what do you mean? This package calls checkForUpdates of built-in electron module internally
