### ISSUE TITLE
Empty warning text

### ISSUE THREAD

**Issue by debelop13** [megahertz/electron-simple-updater#80]
Hi,

My autoupdate is not working,

I have configured logs like this:

> 
    updater.setOptions('logger', {
      debug(text) {
        log.info(`auto-update debug: ${text}`);
      },
      info(text) {
        log.info(`auto-update info: ${text}`);
      },
      warn(text) {
        log.warn(`auto-update warnning: ${text}`);
        self.set('isDownloading', false);
        self.set('message', self.intl.t('auto-update.error-checking'));
        self.set('error', true);
      }
    });

But I receive empty text in warning, and nothing in debug function

What is happening?

Thanks!

**Comment by megahertz** [comment]
Hi, 

It should be like
```js
debug(...text) {
  log.info('auto-update debug:', ...text);
},
```

**Comment by debelop13** [comment]
Thanks, now is ok
