### ISSUE TITLE
Support for download progress (important for slow connections)

### ISSUE THREAD

**Issue by fp07** [megahertz/electron-simple-updater#81]
Can we have support for download progress to inform the user about the state and download percent? Sometimes users have really slow internet and don't get enough feedback about the status of the download. Sometimes it takes more than 10+ minutes and giving users some feedback is something that is necessary, since electron apps are mostly 70+ MB of size.

AutoUpdater which is used under the hood, uses the following code to report the progress:

> autoUpdater.on('download-progress', (progressObj) => {
  let log_message = "Download speed: " + progressObj.bytesPerSecond;
  log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
  log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
  // send log_message to window for example
})

**Comment by megahertz** [comment]
It seems it's an example from electron-updater, which supports this option. But Electron built-in module has no this feature. Maybe I missed something?

**Comment by fp07** [comment]
> It seems it's an example from electron-updater, which supports this option. But Electron built-in module has no this feature. Maybe I missed something?

I see that I misread the documentation. Nonetheless this something that would be appreciated.

**Comment by megahertz** [comment]
Sorry, but I'm not going to make a full-featured solution. For users who really need high-configured updater module it's better to use electron-updater instead.
