### ISSUE TITLE
cannot perform update "Update is disabled because the app is not packaged"

### ISSUE THREAD

**Issue by jyooi** [megahertz/electron-simple-updater#85]
Hi author, I am quite confused
 about this error message from electron-log,  I am running a Linux Appimage with electron-simple-updater also the Appimage was built by the electron-builder package. 

electron-rebuild : v 22.9.1
electron: v 2.0.4

log file 
<img width="743" alt="Screenshot 2021-03-14 at 6 09 06 PM" src="https://user-images.githubusercontent.com/42993221/111064685-60717d80-84f0-11eb-8b8a-e15cbb7827f6.png">

updater in package.json
<img width="816" alt="Screenshot 2021-03-14 at 6 07 37 PM" src="https://user-images.githubusercontent.com/42993221/111064648-2acc9480-84f0-11eb-9281-359b2a15cbed.png">

main.js 
<img width="445" alt="Screenshot 2021-03-14 at 6 07 08 PM" src="https://user-images.githubusercontent.com/42993221/111064639-18eaf180-84f0-11eb-94e2-4c97992247fb.png">

**Comment by jyooi** [comment]
sorry my fault, I build the application without --dir in the electron-builder argument

**Comment by megahertz** [comment]
Is the issue solved? If no, I think you're using old version of electron where app.isPackaged property is not implemented. As a workaround, you can set app.isPackaged = true in the main process.

**Comment by jyooi** [comment]
@megahertz I thought about that too, let me try it out thanks

**Comment by jyooi** [comment]
@megahertz it works thanks
