### ISSUE TITLE
Where can i locate the downlaoded electron packages?

### ISSUE THREAD

**Issue by jyooi** [megahertz/electron-simple-updater#86]
Hi author, may i know where can i locate the downloaded electron packages?

**Comment by megahertz** [comment]
Hi, what do you mean? If you mean where an application update is downloaded using squirrel-windows, if I remember correctly it's %USERPROFILE%/AppData/{appName}-updates, but I'm not sure since it's handled by squirrel, not by this package.

**Comment by jyooi** [comment]
i see, yap i got it thanks a lot @megahertz
