### ISSUE TITLE
error

### ISSUE THREAD

**Issue by smackgg** [megahertz/electron-simple-updater#9]
I don't know why these errors?

```
/Applications/daying.app/Contents/Resources/electron.asar/renderer/api/remote.js:267:16
    at metaToPlainObject (/Applications/daying.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:5)
    at metaToValue (/Applications/daying.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:14)
    at metaToValue (/Applications/daying.app/Contents/Resources/electron.asar/renderer/api/remote.js:203:22)
    at EventEmitter.<anonymous> (/Applications/daying.app/Contents/Resources/electron.asar/renderer/api/remote.js:282:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by megahertz** [comment]
This information is not enough to determine where is the error. What is the error message?
In the stack I see only a problem when calling render process code from browser process.

**Comment by smackgg** [comment]
@megahertz  
I don't know what happened, I only console this error.The console display these error message

![image](https://cloud.githubusercontent.com/assets/13075469/22200927/512cec02-e19c-11e6-90be-1a252bb372f8.png)

So, how can I see error detail?

**Comment by megahertz** [comment]
electron-simple-updater does not contains code which executes in a rendere process. So there is an error in your code. I can assume that you initialize electron-simple-updater in a renderer process instead of a browser process. Sorry, I can't give you an advice without your source code.

**Comment by smackgg** [comment]
This is my code. 
https://github.com/emododododo/daying/commit/6515ffa4a5a1278ea942813540e8749b8853f5c6

Please help me if you have time. Thanks.

**Comment by smackgg** [comment]
But my code is all good.
You can see all code on https://github.com/emododododo/daying/tree/test-release

Commit:
https://github.com/emododododo/daying/commit/6515ffa4a5a1278ea942813540e8749b8853f5c6
https://github.com/emododododo/daying/commit/3c2abe4a2353796f54ae2f3d96a2029529699ed9

Please help me if you have free time, thanks.

**Comment by megahertz** [comment]
Yes, it seems that your code is correct. I'll try to run it tomorrow.

**Comment by megahertz** [comment]
Sorry, I have no time now. But I'll try to help you in a few days.

**Comment by smackgg** [comment]
OK. Thanks.

**Comment by smackgg** [comment]
This is  same problem, same error log.

https://github.com/electron/electron/issues/8294

**Comment by megahertz** [comment]
Maybe it's related to specific electron version. I've run your project on macOS (with changed update url) and it works correctly. I used electron 1.4.15

**Comment by smackgg** [comment]
On your macOS autoUpdate works correctly?
I will use electrion 1.4.15 try it tomorrow...
Спасибо 🐱

**Comment by MathGrelck** [comment]
When I run your example, I'm also getting an 'Error'. 
This is the log output:
```
[info] Start the application
[info] Found version 0.0.2 at https://github.com/megahertz/electron-simple-updater/releases/download/darwin-x64-prod-v0.0.2/release.json
[info] Downloading updates from https://github.com/megahertz/electron-simple-updater/releases/download/darwin-x64-prod-v0.0.2/release.json
[warn] Error
```
I checked with Little Snitch that it manages to download most or all of the v0.0.2 content from github, but then throws an error (maybe when trying to initiate the installation process?).
What I did was to change the version number from 0.0.2 to 0.0.1 in app/package.json, then compile and run the generated .app.
I'm using electron@1.4.15 on OSX 10.11.6
Does it make a difference that the app I compile is code signed with my company credentials (since the one you host on github of course is not)?

**Comment by megahertz** [comment]
@smackgg, yes

@MathGrelck Yes, you need to have the same code sign certificate for the current app and for update.

**Comment by smackgg** [comment]
@megahertz Can't autoUpdate if no sign certificate?

**Comment by megahertz** [comment]
@smackgg As I know, yes, Squirrel.Mac requires code signing, I'm not sure. But I know exactly that update will fail if previous and next version are signed using different certificate.

**Comment by megahertz** [comment]
@smackgg You can try to log error.message instead of error.

**Comment by smackgg** [comment]
![image](https://cloud.githubusercontent.com/assets/13075469/22772178/35716776-eed6-11e6-9fe7-b13dd8f1470c.png)
![image](https://cloud.githubusercontent.com/assets/13075469/22772195/4203d99c-eed6-11e6-88bb-9be9e1c5ee44.png)

Error.message logs noting..
I think the error should because of sign certificate. I have not written any code about the sign certificate.

You say sign certificate need apple developer ？

**Comment by megahertz** [comment]
@smackgg Sure. You need to get certificate and pass it to electron builder.

**Comment by smackgg** [comment]
@megahertz So, only on mac...Windows not ?

**Comment by megahertz** [comment]
@smackgg You can build for windows without a certificate.

**Comment by megahertz** [comment]
@smackgg Did you solve the problem? Or the reason was an empty sign certificate on macOS?

**Comment by smackgg** [comment]
Yep,  It's only because of sign certificate...
